import re
import numpy as np
import pandas as pd


def clean_duration(text):
    if pd.isna(text):
        return np.nan

    text = text.lower().strip()

    try:
        return float(text)
    except:
        pass

    match = re.search(
        r"(\d+(?:[\.,]?\d*)?)\s*[-–—]+\s*(\d+(?:[\.,]?\d*)?)\s*(час|ч|h)?", text
    )
    if match and "недел" in text:
        low = float(match.group(1).replace(",", "."))
        high = float(match.group(2).replace(",", "."))
        return round((low + high) / 2, 2)

    match = re.search(
        r"(\d+(?:[\.,]?\d*)?)\s*(часов|часа|час|ч)\s*(в неделю|/нед)", text
    )
    if match:
        return float(match.group(1).replace(",", "."))

    match = re.search(r"(\d+)\s*минут", text)
    if match and "день" in text:
        minutes_per_day = int(match.group(1))
        return round((minutes_per_day / 60) * 7, 2)

    match = re.search(r"(\d+(?:[\.,]?\d*)?)\s*(час|ч)\s*в\s*день", text)
    if match:
        return round(float(match.group(1).replace(",", ".")) * 7, 2)

    if "в день" in text and "больше" in text:
        return 8

    match = re.search(r"(\d+)\s*час(ов|а)?", text)
    if match and ("видео" in text or "лекц" in text or "практик" in text):
        return round(float(match.group(1)) / 6, 2)  # assuming 6-week course

    match = re.search(
        r"(\d+)\s*(часов|ч)\s*в\s*неделю.*?(\d+(?:[.,]?\d*)?)\s*(месяц|мес)", text
    )
    if match:
        weekly = float(match.group(1))
        months = float(match.group(3).replace(",", "."))
        return weekly

    match = re.search(r"(расчетное время|суммарная нагрузка).*(\d+)", text)
    if match:
        total_hours = int(match.group(2))
        return round(total_hours / 6, 2)

    if "реально пройти за вечер" in text:
        return 3
    if "2 часа вашего времени" in text:
        return 2
    if "2 месяца" in text:
        return 2
    if "1 месяц" in text:
        return round(6, 2)
    if "не более" in text and "дн" in text:
        return 4
    if "время прохождения курса" in text and "недел" in text:
        return 4

    if "60 минут" in text:
        return 1
    if "30 минут" in text:
        return 0.5

    if "аптасына" in text:
        return 1.5

    match = re.search(r"(\d+)\s*(часов|часа|час|ч)", text)
    if match:
        return float(match.group(1))

    return np.nan


def string_to_list(cell):
    if pd.isna(cell) or not isinstance(cell, str):
        return []
    seen = set()
    return [
        x
        for x in [item.strip() for item in cell.split(",")]
        if x and not (x in seen or seen.add(x))
    ]


CATEGORY_IDS = [
    350,
    1,
    2,
    5,
    7,
    8,
    9,
    48,
    120,
    345,
    354,
    356,
    357,
    394,
    395,
    397,
    399,
    400,
    402,
    403,
    404,
    406,
    407,
    412,
    490,
    312,
    366,
    367,
    368,
    360,
    370,
    371,
    372,
    373,
    34,
    32,
    46,
    187,
    418,
    415,
    413,
    416,
    417,
    418,
    419,
    420,
    421,
    87,
    88,
    89,
    90,
    419,
    499,
    331,
    500,
    501,
    502,
    503,
    504,
    481,
    482,
    483,
    484,
    485,
    486,
    487,
    488,
]

SOFTWARE_KEYWORDS = [
    "Python",
    "Java",
    "JavaScript",
    "C#",
    "Ruby",
    "PHP",
    "TypeScript",
    "Go",
    "Rust",
    "Kotlin",
    "Swift",
    "R",
    "React",
    "Vue.js",
    "Angular",
    "Flask",
    "Django",
    "Spring",
    "Express.js",
    "Pandas",
    "NumPy",
    "Matplotlib",
    "TensorFlow",
    "PyTorch",
    "jQuery",
    "Visual Studio Code",
    "IntelliJ IDEA",
    "Eclipse",
    "NetBeans",
    "Xcode",
    "Sublime Text",
    "PyCharm",
    "Atom",
    "Notepad++",
    "Git",
    "GitHub",
    "GitLab",
    "Jupyter Notebook",
    "HTML",
    "CSS",
    "JavaScript",
    "Bootstrap",
    "Sass",
    "Tailwind CSS",
    "WordPress",
    "Wix",
    "Squarespace",
    "Figma",
    "Sketch",
    "Adobe XD",
    "Chrome Developer Tools",
    "Webpack",
    "Nginx",
    "Apache",
    "Android Studio",
    "Xcode",
    "React Native",
    "Flutter",
    "Xamarin",
    "Cordova",
    "Swift",
    "Kotlin",
    "Java",
    "Objective-C",
    "Ionic",
    "Figma",
    "Unity",
    "Unreal Engine",
    "Godot",
    "CryEngine",
    "Blender",
    "3ds Max",
    "Maya",
    "Cocos2d",
    "GameMaker Studio",
    "Construct",
    "GIMP",
    "ZBrush",
    "Excel",
    "Power BI",
    "Tableau",
    "Python",
    "R",
    "SQL",
    "Apache Spark",
    "Hadoop",
    "Jupyter Notebooks",
    "MATLAB",
    "Google Analytics",
    "Looker",
    "Alteryx",
    "TensorFlow",
    "PyTorch",
    "Keras",
    "Scikit-learn",
    "OpenCV",
    "NLTK",
    "SpaCy",
    "GPT-3",
    "Dialogflow",
    "IBM Watson",
    "Rasa",
    "Botpress",
    "Microsoft Bot Framework",
    "Selenium",
    "JUnit",
    "TestNG",
    "Appium",
    "Postman",
    "SoapUI",
    "Apache JMeter",
    "TestComplete",
    "Jenkins",
    "GitLab CI",
    "Bamboo",
    "Travis CI",
    "Cucumber",
    "Figma",
    "Sketch",
    "Adobe XD",
    "InVision",
    "Balsamiq",
    "Zeplin",
    "Marvel",
    "Principle",
    "Proto.io",
    "Fluid UI",
    "Jira",
    "Trello",
    "Asana",
    "Monday.com",
    "Slack",
    "Confluence",
    "Microsoft Teams",
    "Basecamp",
    "GitHub Issues",
    "Targetprocess",
    "Agile",
    "Scrum" "Docker",
    "Kubernetes",
    "Ansible",
    "Jenkins",
    "GitLab CI",
    "Terraform",
    "AWS",
    "Azure",
    "Google Cloud Platform",
    "Prometheus",
    "Nagios",
    "Zabbix",
    "Puppet",
    "Chef",
    "Vagrant",
    "Nginx",
    "Apache",
    "Wireshark",
    "Metasploit",
    "Kali Linux",
    "Burp Suite",
    "Nessus",
    "Snort",
    "Nmap",
    "John the Ripper",
    "OpenSSL",
    "TrueCrypt",
    "GPG",
    "Adobe Illustrator",
    "CorelDRAW",
    "Figma",
    "Inkscape",
    "Affinity Designer",
    "Gravit Designer",
    "Sketch",
    "Canva",
    "Blender",
    "3ds Max",
    "Maya",
    "Cinema 4D",
    "ZBrush",
    "Houdini",
    "Substance Painter",
    "DALL-E",
    "Inkscape",
    "Adobe Illustrator",
    "Corel Painter",
    "Clip Studio Paint",
    "Procreate",
    "Krita",
    "Figma",
    "Adobe XD",
    "Sketch",
    "Webflow",
    "Wix",
    "WordPress",
    "Elementor",
    "Adobe After Effects",
    "Blender",
    "Autodesk Maya",
    "Toon Boom Harmony",
    "Cinema 4D",
    "Moho Pro",
    "TVPaint Animation",
    "Adobe Premiere Pro",
    "Final Cut Pro",
    "DaVinci Resolve",
    "Sony Vegas",
    "HitFilm Express",
    "Avid Media Composer",
    "Ableton Live",
    "FL Studio",
    "Logic Pro",
    "Pro Tools",
    "Cubase",
    "Audacity",
    "Adobe Audition",
    "Blender",
    "Autodesk Maya",
    "3ds Max",
    "ZBrush",
    "Cinema 4D",
    "Rhino",
    "AutoCAD",
    "SketchUp",
    "Revit",
    "ArchiCAD",
    "Rhino",
    "3ds Max",
    "V-Ray",
    "Математика",
    "Физика",
    "Химия",
    "Биология",
    "Генетика",
    "Нейро",
    "макияж",
    "прически",
    "мода",
    "стиль",
    "уход за кожей",
    "косметология",
    "визаж",
    "маникюр",
    "парикмахерское дело",
    "кинематография",
    "актерское мастерство",
    "сценарное мастерство",
    "режиссура",
    "монтаж",
    "театральное искусство",
    "сценическая речь",
    "драматургия",
    "музыка",
    "танец",
    "вокал",
    "хореография",
    "игра на гитаре",
    "фортепиано",
    "сольфеджио",
    "композиция",
    "балет",
    "джаз",
    "импровизация",
    "рисование",
    "живопись",
    "графика",
    "акварель",
    "иллюстрация",
    "скетчинг",
    "дизайн",
    "каллиграфия",
    "декоративно-прикладное искусство",
    "фотография",
    "видеосъемка",
    "постобработка",
    "композиция",
    "свет",
    "камера",
    "ретушь",
    "видеомонтаж",
    "съемка дронами",
    "туризм",
    "планирование поездок",
    "трекинг",
    "культурология",
    "путешествия",
    "навигация",
    "путешествия по миру",
    "организация туров",
    "кинология",
    "уход за животными",
    "дрессировка",
    "ветеринария",
    "поведение животных",
    "аквариумистика",
    "кормление",
    "фитнес",
    "тренировки",
    "бодибилдинг",
    "кардио",
    "силовые упражнения",
    "растяжка",
    "тренерская работа",
    "функциональный тренинг",
    "здоровье",
    "правильное питание",
    "диетология",
    "профилактика",
    "медицинские знания",
    "образ жизни",
    "йога",
    "дыхательные практики",
    "медитация",
    "асаны",
    "пранаяма",
    "йогатерапия",
    "психология",
    "стресс-менеджмент",
    "самопомощь",
    "тревожность",
    "эмоциональный интеллект",
    "психотерапия",
    "медицина",
    "уход за больными",
    "сестринское дело",
    "эпидемиология",
    "анатомия",
    "фармакология",
    "первая помощь",
    "сердечно-легочная реанимация",
    "оказание помощи",
    "аварийные ситуации",
    "аптечка",
    "спасательные навыки",
    "математика",
    "алгебра",
    "геометрия",
    "логика",
    "теория вероятностей",
    "статистика",
    "вычисления",
    "дифференциальное исчисление",
    "химия",
    "органическая химия",
    "неорганическая химия",
    "лабораторные навыки",
    "реакции",
    "молекулы",
    "периодическая таблица",
    "биология",
    "клеточная биология",
    "эволюция",
    "зоология",
    "ботаника",
    "микробиология",
    "экология",
    "физиология",
    "генетика",
    "ДНК",
    "наследственность",
    "генная инженерия",
    "геномика",
    "мутации",
    "молекулярная биология",
    "когнитивные процессы",
    "поведение",
    "эмоции",
    "развитие личности",
    "нейропсихология",
    "психоанализ",
    "история",
    "археология",
    "мировая история",
    "история России",
    "исторические события",
    "культура",
    "исторические личности",
    "философия",
    "логика",
    "этика",
    "метафизика",
    "эпистемология",
    "философские школы",
    "критическое мышление",
    "социология",
    "общество",
    "социальные группы",
    "демография",
    "социологические исследования",
    "экономика",
    "макроэкономика",
    "микроэкономика",
    "финансы",
    "инвестиции",
    "бухгалтерия",
    "инфляция",
    "рынок",
    "архитектура",
    "черчение",
    "проектирование",
    "инженерия",
    "строительство",
    "CAD",
    "конструкционные материалы",
    "дизайн зданий",
]
